name: brep2x
channels:
  - pytorch
  - dglteam/label/cu121
  - nvidia
  - conda-forge
  - lambouj
  - defaults
dependencies:
  - pytorch=2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - dgl=2.0.0.cu121=py310_0
  - occwl=3.0.0=py_0
  - pip=23.2.1
  - fairseq=0.12.3
  - pip:
      - pytorch-lightning==1.9.1
      - torch-geometric==2.3.1
      - numpy==1.23.5
      - torchvision==0.16.0
      - torchaudio==2.1.0
      - tensorboardX==2.6.0
      - tensorboard
      
      
